 
image:
    file: .gitpod.dockerfile
  ports:
    - port: 3000
      onOpen: open-preview
  tasks:
    - init: >
        bundle install --without production &&
        cp config/database.yml.example config/database.yml &&
        cp db/schema.rb.example db/schema.rb &&
        bundle exec rake db:schema:load &&
        bundle exec rake db:migrate
      command: >
        rails server
        sidekiq

    github:
    prebuilds:
        # enable for the master/default branch (defaults to true)
        master: true
        # enable for all branches in this repo (defaults to false)
        branches: true
        # enable for pull requests coming from this repo (defaults to true)
        pullRequests: true
        # enable for pull requests coming from forks (defaults to false)
        pullRequestsFromForks: true
        # add a check to pull requests (defaults to true)
        addCheck: true
        # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
        addComment: false
        # add a "Review in Gitpod" button to the pull request's description (defaults to false)
        addBadge: false
        # add a label once the prebuild is ready to pull requests (defaults to false)
        addLabel: false
    vscode:
        extensions:
            - connorshea.vscode-ruby-test-adapter@0.6.1:HO9rpcRv7bmRIuo7Mty/zg==
            - hbenl.vscode-test-explorer@2.15.0:koqDUMWDPJzELp/hdS/lWw==
