image:
    file: .gitpod.dockerfile
ports:
    - port: 3000
      onOpen: open-preview
tasks:
    - init: >
        bundle install --without production &&
        cp config/database.yml.gitpod config/database.yml &&
        cp db/schema.rb.example db/schema.rb &&
        rake db:setup
        yarn install

      command: >
        bundle exec passsenger start

github:
    prebuilds:
        branches: true
        pullRequests: true
        pullRequestsFromForks: true
        addCheck: true
        addComment: true
        addBadge: false
        addLabel: false
