image:
    file: .gitpod.dockerfile
ports:
    - port: 3000
      onOpen: open-preview
tasks:
    - init: >
        bundle install --without production &&
        cp config/dabase.yml.gitpod config/database.yml &&
        cp db/schema.rb.example db/schema.rb &&
        rake db:setup 

      command: >
        passsenger start

github:
    prebuilds:
        pullRequestsFromForks: true

