image:
    file: .gitpod.dockerfile
ports:
    - port: 3000
      onOpen: open-preview
tasks:
    - init: >
        bundle install --without production &&
        cp config/database.yml.example config/database.yml &&
        cp db/schema.rb.example db/schema.rb &&
        rails db:migrate
      command: >
        rails server

github:
    prebuilds:
        pullRequestsFromForks: true

